import quadtree as qt
import os
import glob
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime
from argparse import ArgumentParser
import re

def plotdir(dirtoplot):
    file_list = glob.glob(dirtoplot + "/*.pkl")
    no_exp = len(file_list)
    rs = np.ceil(np.sqrt(no_exp)).astype(np.int)
    cls = np.ceil(no_exp / rs).astype(np.int)
    fig, axs = plt.subplots(rs, cls)
    for i, f in enumerate(file_list):
        exp = resolvename(f)
        c = i % cls
        r = i // cls
        t = qt.Quadtree.load(f)
        print("loading tree {} done. proceeding with pruning".format(exp))
        t.postprocess()
        print("pruning tree {} done. Proceeding with plotting".format(exp))
        t.plot_tree(axs[r,c])
        axs[r,c].set_title(exp)
    
    plt.show()

def findexp(exp_name, directory):
    # file_list = glob.glob(directory + "*{}*".format(exp_name))
    file_list = [f for f in os.listdir(directory) if exp_name in f and ".pkl" in f]
    return file_list

def resolvename(f):
    fname = f.split("/")[-1]
    date_exp = fname.split("-")[3:5]
    exp = "_".join(date_exp)
    return exp

def compareexp(directory, exp_list, title="", depth=10):
    exp_ct = len(exp_list)
    tree_dict = {}
    for exp_fn in exp_list:
        fname = os.path.join(directory, exp_fn)
        tree = qt.Quadtree.load(fname)
        # tree.postprocess(depth=depth)
        exx = regexFilename(fname)
        skip = int(exx.split("-")[-1])
        fr = getFreq(skip, title)
        tree_dict[fr] = tree
    print("Loading trees and pruning for {} done, continuing with KL comparison and plotting".format(
        title
    ))
    base_freq = getBaseFreq(title)
    base_tree = tree_dict[base_freq]
    del tree_dict[base_freq]
    kl_dict = {}
    for k, v in tree_dict.items():
        kl_dict[k] = compareTwoTrees(base_tree, tree_comp=v)
    x = np.asarray(list(kl_dict.keys()))
    y = np.asarray(list(kl_dict.values()))
    fig = plt.figure(figsize=(15,9))
    ax = fig.gca()
    ax.plot(x, y, '-x')
    # ax.scatter(x, y, 'x')
    ax.set_title("KL-Div {}: {}".format(title, depth))

    plt.show()


def compareTwoTrees(tree_base : qt.Quadtree, tree_comp: qt.Quadtree):
    """
        ! Base SHOULD be a superclass of the other tree - because the other tree just SKIPS these observations -> assume that the same indices are in there. So iterate over that set of indices and check if they are present in the other dictionary
        ! add the keys that have been checked to a set, so that we can later check how many are NOT in the tree.
        TODO: potentially add the level to the KL-DIV. check whether that level has an influence
    """
    inters = tree_base.dictionary.keys() & tree_comp.dictionary.keys()
    full = tree_base.dictionary.keys() | tree_comp.dictionary.keys()
    not_inters = full - inters
    kl = 0
    for k in inters:
        base = tree_base[k].getprobabilities()
        comp = tree_comp[k].getprobabilities()
        l = tree_base.getlevel(k)
        kl += kl_div(base, comp)
    return kl


def regexFilename(name):
    out = re.search(r'qt-(\d?)',name)
    return out.group()

def getFreq(skip, title):
    di = getBaseFreq(title)
    return int(di / skip)

def getBaseFreq(title):
    if "exp" in title:
        return 24
    else:
        return 32

def kl_div(vec_true, vec_pred):
    """
    use the definition of the KL divergence
        https://en.wikipedia.org/wiki/Kullback%E2%80%93Leibler_divergence
        * look at octomap paper for their defintion - the same!
    """
    kl = np.sum(np.log(vec_true / vec_pred) * vec_true)
    return kl
    # negative cross-entropy
    # return np.sum(vec_true*np.log(vec_pred)) * (-1.0)

def parse_args(defaultdir):
    """
        Function to parse the arguments 
    """
    parser = ArgumentParser(description="Plotting two quadtrees that have been generated by the same file.")
    parser.add_argument("-d", "--depth", help="Plotting depth of the quadtree. Default is 1.", type=int,default=4)
    parser.add_argument("--input", help="Input directory. Default is the one of the file", type=str, default=defaultdir)
    parser.add_argument("--file", help="Input Experiment. Used to read the file which contains the string given by file from input directory. If not specified will raise FileNotFoundError", type=str, default="exp_tgt2-descend")
    args = parser.parse_args()
    return args

if __name__=="__main__":
    thisdir = os.path.dirname(__file__)
    # a = datetime(2021, 10, 8)
    # outdir_date = a.strftime("%y-%m-%d")
    defdir = os.path.join(thisdir, '..', 'output', 'hpc', "skip")
    args = parse_args(defdir)
    
    f = findexp(args.file, args.input)
    compareexp(args.input, f, args.file, depth=args.depth)
    # cform = c.strftime("%y-%m-%d")
    # dirtoplot = os.path.abspath(os.path.join(thisdir, '..', 'output', cform))
    # plotdir(dirtoplot)
    
    print("Plotting done")